site_name: MEI

repo_name: '2022.2-MEI'
repo_url: https://github.com/Requisitos-de-Software/2022.2-MEI

theme:
  name: material
  language: pt-BR
  font:
    text: Roboto
  
  palette: 
    - scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.indexes

nav:
  - Planejamento:
    - Home: index.md
    - Aplicativos Analisados: Planejamento/AplicativosAnalisados.md
    - Aplicativo Escolhido: Planejamento/MEI.md
    - Metodologias e Processos: Planejamento/Metodologia.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Heatmap: Planejamento/Heatmap.md
    - Roadmap: Planejamento/Roadmap.md
    - Políticas:
      - Código de Conduta Para Colaboradores: Politicas/CodigoDeConduta.md
      - Política de Contribuição: Politicas/PolitcaDeContribuicao.md
      - Política de Issue: Politicas/PolitcaDeIssue.md
      - Política de Branch: Politicas/PolitcaDeBranch.md
      - Política de Commit: Politicas/PolitcaDeCommit.md
      - Política de Pull Request: Politicas/PolitcaDePR.md
      - Política de Segurança: Politicas/PolitcaDeSeguranca.md
    - Cronograma de Elicitação/Priorização: Elicitacao/Cronogramas.md
    - Termo de consentimento: Elicitacao/ModeloTermoConsentimento.md
  - Apresentações/Reuniões:
    - Introdução: Reunioes/index.md
    - Apresentações:
      - 1º Ponto de Controle: Reunioes/Apresentacoes/PrimeiraEntrega.md
      - 2º Ponto de Controle: Reunioes/Apresentacoes/SegundaEntrega.md
      - 3º Ponto de Controle: Reunioes/Apresentacoes/TerceiraEntrega.md
      - 4º Ponto de Controle: Reunioes/Apresentacoes/QuartaEntrega.md
      - 5º Ponto de Controle: Reunioes/Apresentacoes/QuintaEntrega.md
    - Reuniões:
      - 1ª Reunião: Reunioes/Atas/Reuniao1.md
      - 2ª Reunião: Reunioes/Atas/Reuniao2.md
      - 3ª Reunião: Reunioes/Atas/Reuniao3.md
      - 4ª Reunião: Reunioes/Atas/Reuniao4.md
      - 5ª Reunião: Reunioes/Atas/Reuniao5.md
      - 6ª Reunião: Reunioes/Atas/Reuniao6.md
  - Elicitação: 
    - Técnicas de Elicitação: Elicitacao/index.md
    - Brainstorming: Elicitacao/Brainstorming.md
    - Entrevista: Elicitacao/Entrevista.md
    - Introspecção: Elicitacao/Introspeccao.md
    - Perfil de Usuário: Elicitacao/perfil.md
    - Persona: Elicitacao/personas.md
    - Priorização: Elicitacao/tecnicas-priorizacao.md
  - Modelagem:
    - Cenários: Modelagem/Cenarios.md
    - Léxicos: Modelagem/Lexicos.md
    - Casos de Uso: Modelagem/CasosdeUso.md
    - Especificação Suplementar: Modelagem/EspecificacaoSuplementar.md
    - NFR Framework: Modelagem/NFRFramework.md
    - Modelo Ágil:
      - Histórias de Usuário: Modelagem/UserCases.md
      - Backlog: Modelagem/Agil/BacklogDoProduto.md
  - Análise:
    - Introdução: Analise/index.md
    - Identificação De Partes: Analise/IdentificaçãoDePartes.md
    - Verificação:
      - Introdução: Analise/Verificacao/index.md
    - Validação: 
      - Introdução: Analise/Validacao/index.md
    - Linkedin:
      - Verificação:
        - Introdução: Analise/Linkedin/Verificacao/index.md
        - Rich Picture: Analise/Linkedin/Verificacao/VerificacaoRichPicture.md
        - Personas: Analise/Linkedin/Verificacao/VerificacaoPersonas.md
        - Backlog: Analise/Linkedin/Verificacao/VerificacaoBacklog.md
        - Casos de uso: Analise/Linkedin/Verificacao/VerificaçãoCasosDeUso.md
        - Cenários: Analise/Linkedin/Verificacao/VerificacaoCenarios.md
        - Priorização de Requisitos: Analise/Linkedin/Verificacao/VerificacaoTecnicasPriorizacao.md
        - NFR: Analise/Linkedin/Verificacao/VerificacaoNFR.md
        - User Stories: Analise/Linkedin/Verificacao/VerificaçãoUserHistories.md
        - Especificação Suplementar: Analise/Linkedin/Verificacao/VerificacaoEspecificacaoSuplementar.md
        - Lexicos: Analise/Linkedin/Verificacao/VerificacaoLexicos.md
        - Planejamento: Analise/Linkedin/Verificacao/VerificacaoPlanejamento.md
        - Tecnicas de Elicitação: Analise/Linkedin/Verificacao/VerificacaoTecnicasElicitacao.md
        - Tecnicas de Priorização: Analise/Linkedin/Verificacao/VerificacaoTecnicasPriorizacao.md
      - Validação: 
        - Introdução: Analise/Linkedin/Validacao/index.md
        - Validação Informal: Analise/Linkedin/Validacao/informal.md